### ISSUE TITLE
useEventListener is not using unrefElement as its ref resolver

### ISSUE THREAD

**Issue by hikariNTU** [vueuse/vueuse#1404]
### Describe the bug

As title, `useEventListener` is accepting a `MaybeRef` element.
But when given with a component ref, it will break directly since the element is wrap inside `$el`, which `unrefElement` will take care about it.

https://github.com/vueuse/vueuse/blob/0382f31574b52af021693021cdfc9c306ed9a1ae/packages/core/useEventListener/index.ts#L102

Currently we use additional unrefElement with computed with it:
```js
// all composable with useEventListener suffer from this problem
useScroll(computed(() => unrefElement(componentRef)));
```

I am wondering why `useEventListener` didn't use `unrefElement` as its implementation. Is there any performance issue or its a bad practice to implicitly transform this for user?

**Similar Question**

- #1103 
- #763

**Backlog Error** (for search engine)
```
Uncaught (in promise) TypeError: el.addEventListener is not a function
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-kdcep9?file=src%2FApp.vue

### System Info

```Shell
System:
  OS: Windows 10 10.0.19044
  CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
  Memory: 42.97 GB / 63.94 GB
Binaries:
  Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
  npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.56)
  Internet Explorer: 11.0.19041.1202
npmPackages:
  @vueuse/core: ^7.0.0 => 7.6.0
  vue: ^3.2.26 => 3.2.30
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [ ] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
