### ISSUE TITLE
No matching export in "node_modules/vue-demi/lib/index.mjs" for import "effectScope"

### ISSUE THREAD

**Issue by littlecxm** [vueuse/vueuse#677]
i wanna use `@vueuse/core` `useTitle` to change my page title
but throw error when i only install it..
use `vueuse 6.0.0` & `vue 3.0.4` & `vite 2.4.4`
```
(this will be run only when your dependencies or config have changed)
 > node_modules/@vueuse/shared/index.esm.js:1:64: error: No matching export in "node_modules/vue-demi/lib/index.mjs" for import "effectScope"
    1 │ ...puted, unref, watch, ref, customRef, isVue3, isRef, effectScope, onScopeDispose, reactive, toRef, isVue2, toRefs a...
      ╵                                                        ~~~~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:77: error: No matching export in "node_modules/vue-demi/lib/index.mjs" for import "onScopeDispose"
    1 │ ...atch, ref, customRef, isVue3, isRef, effectScope, onScopeDispose, reactive, toRef, isVue2, toRefs as toRefs$1, get...
      ╵                                                      ~~~~~~~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:179: error: No matching export in "node_modules/vue-demi/lib/index.mjs" for import "getCurrentScope"
    1 │ ... isVue2, toRefs as toRefs$1, getCurrentInstance, onMounted, nextTick, getCurrentScope, onUnmounted } from 'vue-demi';
      ╵                                                                          ~~~~~~~~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:131: error: No matching export in "node_modules/vue-demi/lib/index.mjs" for import "getCurrentScope"
    1 │ ...urrentInstance, onMounted, onUpdated, shallowRef, getCurrentScope, reactive, markRaw, readonly, onBeforeUpdate, is...
      ╵                                                      ~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 4 errors:
node_modules/@vueuse/core/index.esm.js:1:131: error: No matching export in "node_modules/vue-demi/lib/index.mjs" for import "getCurrentScope"
node_modules/@vueuse/shared/index.esm.js:1:64: error: No matching export in "node_modules/vue-demi/lib/index.mjs" for import "effectScope"
node_modules/@vueuse/shared/index.esm.js:1:77: error: No matching export in "node_modules/vue-demi/lib/index.mjs" for import "onScopeDispose"
node_modules/@vueuse/shared/index.esm.js:1:179: error: No matching export in "node_modules/vue-demi/lib/index.mjs" for import "getCurrentScope"

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

*edit: I downgrade vueuse -> `^5.3.0` it works

**Comment by littlecxm** [comment]
it works when I upgrade Vue to 3.2.4

**Comment by itpropro** [comment]
I have the same problem with Nuxt, which uses vue 2, so no possibility to upgrade. Can you reopen this issue plese @littlecxm ?
`
client.js?1b93:196 ./node_modules/@vueuse/shared/index.esm.js 210:18-29"export 'effectScope' was not found in 'vue-demi'./node_modules/@vueuse/shared/index.esm.js 240:20-31"export 'effectScope' was not found in 'vue-demi'./node_modules/@vueuse/core/index.esm.js 1170:18-33"export 'getCurrentScope' was not found in 'vue-demi'./node_modules/@vueuse/shared/index.esm.js 746:8-23"export 'getCurrentScope' was not found in 'vue-demi'./node_modules/@vueuse/shared/index.esm.js 243:8-22"export 'onScopeDispose' was not found in 'vue-demi'./node_modules/@vueuse/shared/index.esm.js 747:8-22"export 'onScopeDispose' was not found in 'vue-demi'
`

**Comment by antfu** [comment]
`@vue/composition-api` v1.1 implemented `effectScope`.

**Comment by antfu** [comment]
https://github.com/nuxt-community/composition-api/commit/0edd3b70b872cd6916134c1ed6c2d957800a0719
