### ISSUE TITLE
web-bluetooth dependency should be transitive

### ISSUE THREAD

**Issue by sanyarnd** [vueuse/vueuse#1704]
### Describe the bug

Without `"@types/web-bluetooth": "0.0.14",` in my `devDependencies` the build fails with:

```
.....

node_modules/@vueuse/core/index.d.ts:396:32 - error TS2304: Cannot find name 'BluetoothDevice'.

396         onserviceadded: (this: BluetoothDevice, ev: Event) => any;
                                   ~~~~~~~~~~~~~~~

node_modules/@vueuse/core/index.d.ts:397:34 - error TS2304: Cannot find name 'BluetoothDevice'.

397         onservicechanged: (this: BluetoothDevice, ev: Event) => any;
                                     ~~~~~~~~~~~~~~~

node_modules/@vueuse/core/index.d.ts:398:34 - error TS2304: Cannot find name 'BluetoothDevice'.

398         onserviceremoved: (this: BluetoothDevice, ev: Event) => any;
                                     ~~~~~~~~~~~~~~~

node_modules/@vueuse/core/index.d.ts:401:26 - error TS2304: Cannot find name 'BluetoothRemoteGATTServer'.

401     server: vue_demi.Ref<BluetoothRemoteGATTServer | undefined>;
                             ~~~~~~~~~~~~~~~~~~~~~~~~~
```

Project uses TypeScript.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 13.45 GB / 31.73 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.1.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.12.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.44)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: 8.7.4 => 8.7.4
    vue: 3.2.37 => 3.2.37
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Shinigami92** [comment]
Seems it's not solved via `v8.7.5` 🙁 

```
node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:340:15 - error TS2304: Cannot find name 'BluetoothLEScanFilter'.

340     filters?: BluetoothLEScanFilter[] | undefined;
                  ~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:348:24 - error TS2304: Cannot find name 'BluetoothServiceUUID'.

348     optionalServices?: BluetoothServiceUUID[] | undefined;
                           ~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:376:36 - error TS2304: Cannot find name 'BluetoothRemoteGATTServer'.

376             connect: () => Promise<BluetoothRemoteGATTServer>;
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:378:42 - error TS2304: Cannot find name 'BluetoothServiceUUID'.

378             getPrimaryService: (service: BluetoothServiceUUID) => Promise<BluetoothRemoteGATTService>;
                                             ~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:378:75 - error TS2304: Cannot find name 'BluetoothRemoteGATTService'.

378             getPrimaryService: (service: BluetoothServiceUUID) => Promise<BluetoothRemoteGATTService>;
                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:379:44 - error TS2304: Cannot find name 'BluetoothServiceUUID'.

379             getPrimaryServices: (service?: BluetoothServiceUUID | undefined) => Promise<BluetoothRemoteGATTService[]>;
                                               ~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:379:89 - error TS2304: Cannot find name 'BluetoothRemoteGATTService'.

379             getPrimaryServices: (service?: BluetoothServiceUUID | undefined) => Promise<BluetoothRemoteGATTService[]>;
                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:383:41 - error TS2304: Cannot find name 'WatchAdvertisementsOptions'.

383         watchAdvertisements: (options?: WatchAdvertisementsOptions | undefined) => Promise<void>;
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:387:63 - error TS2304: Cannot find name 'BluetoothDevice'.

387             (type: "gattserverdisconnected", listener: (this: BluetoothDevice, ev: Event) => any, useCapture?: boolean | undefined): void;
                                                                  ~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:388:62 - error TS2304: Cannot find name 'BluetoothDevice'.

388             (type: "advertisementreceived", listener: (this: BluetoothDevice, ev: BluetoothAdvertisingEvent) => any, useCapture?: boolean | undefined): void;
                                                                 ~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:388:83 - error TS2304: Cannot find name 'BluetoothAdvertisingEvent'.

388             (type: "advertisementreceived", listener: (this: BluetoothDevice, ev: BluetoothAdvertisingEvent) => any, useCapture?: boolean | undefined): void;
                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:393:41 - error TS2304: Cannot find name 'BluetoothDevice'.

393         onadvertisementreceived: (this: BluetoothDevice, ev: BluetoothAdvertisingEvent) => any;
                                            ~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:393:62 - error TS2304: Cannot find name 'BluetoothAdvertisingEvent'.

393         onadvertisementreceived: (this: BluetoothDevice, ev: BluetoothAdvertisingEvent) => any;
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:394:42 - error TS2304: Cannot find name 'BluetoothDevice'.

394         ongattserverdisconnected: (this: BluetoothDevice, ev: Event) => any;
                                             ~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:395:46 - error TS2304: Cannot find name 'BluetoothDevice'.

395         oncharacteristicvaluechanged: (this: BluetoothDevice, ev: Event) => any;
                                                 ~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:396:32 - error TS2304: Cannot find name 'BluetoothDevice'.

396         onserviceadded: (this: BluetoothDevice, ev: Event) => any;
                                   ~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:397:34 - error TS2304: Cannot find name 'BluetoothDevice'.

397         onservicechanged: (this: BluetoothDevice, ev: Event) => any;
                                     ~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:398:34 - error TS2304: Cannot find name 'BluetoothDevice'.

398         onserviceremoved: (this: BluetoothDevice, ev: Event) => any;
                                     ~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:401:26 - error TS2304: Cannot find name 'BluetoothRemoteGATTServer'.

401     server: vue_demi.Ref<BluetoothRemoteGATTServer | undefined>;
                             ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 19 errors in the same file, starting at: node_modules/.pnpm/@vueuse+core@8.7.5_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:340
```

**Comment by MrCube42** [comment]
Can confirm this: We still have the same problem even after upgrading to 8.7.5+ (using vue 2.6.14 and @vue/composition-api 1.4.3). We get the same error from the d.ts files as reported above https://github.com/vueuse/vueuse/issues/1704#issuecomment-1164323355.

**Comment by ch1035063420** [comment]
The upgrade to 8.7.5 is still unresolved

**Comment by holtwick** [comment]
Also still seeing this when using "vue-tsc --noEmit"

**Comment by holtwick** [comment]
Any updates on this? In "@vueuse/core": "^9.1.0" I still see the error.

I was able to mitigate it by installing "@types/web-bluetooth" and adding "web-bluetooth" to "compilerOptions.types" in tsconfig.json, but it is a bit annoying to have this kind of workaround, since most users very likely are not using bluetooth features of the lib at all. Maybe this could become a separate package?

**Comment by MrCube42** [comment]
> Can confirm this: We still have the same problem even after upgrading to 8.7.5+ (using vue 2.6.14 and @vue/composition-api 1.4.3). We get the same error from the d.ts files as reported above [#1704 (comment)](https://github.com/vueuse/vueuse/issues/1704#issuecomment-1164323355).

FYI: We updated to @vueuse/core 9.0.0 (using vue 2.6.14 and @vue/composition-api 1.7.0, still using vue-cli to build) and the error is gone without any extra adjustmenst.

**Comment by holtwick** [comment]
Thanks @MrCube42 for the feedback. I still saw the issues with the latest versions of all packages (on macOS, package manager `pnpm`), but maybe this is just a local setup issue. Never mind, the workaround is fine for me ;)

```
> vue-tsc --noEmit -p ./tsconfig.json

node_modules/.pnpm/@vueuse+core@9.1.0_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:368:15 - error TS2304: Cannot find name 'BluetoothLEScanFilter'.

368     filters?: BluetoothLEScanFilter[] | undefined;
                  ~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@9.1.0_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:376:24 - error TS2304: Cannot find name 'BluetoothServiceUUID'.

376     optionalServices?: BluetoothServiceUUID[] | undefined;
                           ~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@9.1.0_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:399:17 - error TS2304: Cannot find name 'BluetoothDevice'.

399     device: Ref<BluetoothDevice | undefined>;
                    ~~~~~~~~~~~~~~~

node_modules/.pnpm/@vueuse+core@9.1.0_vue@3.2.37/node_modules/@vueuse/core/index.d.ts:401:17 - error TS2304: Cannot find name 'BluetoothRemoteGATTServer'.

401     server: Ref<BluetoothRemoteGATTServer | undefined>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by radusuciu** [comment]
Also have this issue in 9.1.0. Workaround;

1. Add two dev dependencies to `package.json`: 
```
        "@babel/types": "^7.18.10",
        "@types/web-bluetooth": "^0.0.15",
```

2. Add `web-bluetooth` to `compilerOptions.types` in `tsconfig.json`.

I do not need any bluetooth related features, and had to add `@babel/types` since there were also some errors related to that..

**Comment by tkzt** [comment]
Also encounter this, my workaround:

```
// tsconfig.json
{
  "compilerOptions": {
    ...
    "skipLibCheck": true
    ...
  }
}
```

**Comment by radusuciu** [comment]
Still see this with version 10.1.2. One more thing to add to my previous comment: `@types/web-bluetooth` is not necessary in `package.json`, but it is still required in `tsconfig.json`.

`skipLibCheck: true` in `tsconfig.json` works as well but that seems like too broad a solution for this specific problem as it could potentially bury legitimate errors related to other packages as well.

**Comment by troyere** [comment]
The problem is still there with 10.7.2

- Add `skipLibCheck: true` : ...seriously ? In 2023, we're still there ? 
- Add `"@types/web-bluetooth": "^0.0.15"` ? I'm using vue use core, there is no way in hell I'll add that if my app does not even use bluetooth features

**Comment by troyere** [comment]
Got it, the problem was in my tsconfig files. 

Still, don't do "that" (https://github.com/vueuse/vueuse/issues/1704#issuecomment-1907807897 !)

**Comment by zymotik** [comment]
This fixed it for me:
https://github.com/vueuse/vueuse/issues/1709#issuecomment-2097035540

**Comment by RTM909** [comment]
I'm getting this when using firebase functions, unable to fix it with the solutions mentioned here. 

> Got it, the problem was in my tsconfig files.
> 
> Still, don't do "that" ([#1704 (comment)](https://github.com/vueuse/vueuse/issues/1704#issuecomment-1907807897) !)

@troyere what fixed it for you?

**Comment by Anoesj** [comment]
@troyere Curious here too!
